# Make sure to install all dependencies (not needed if already done):
install.packages("SqlRender")
install.packages("DatabaseConnector")
install.packages("ParallelLogger")
install.packages("readr")
install.packages("tibble")
install.packages("dplyr")
install.packages("RJSONIO")
install.packages("devtools")
install.packages("rlang")
install.packages("reticulate")
install.packages('Rcpp')
devtools::install_github("ROhdsiWebApi")
devtools::install_github("CohortDiagnostics")

install.packages("drat")
drat::addRepo("OHDSI")
install.packages("OhdsiSharing")